-- 1. Create Projects Table (If not exists)
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title_ar text not null,
  title_en text not null,
  description_ar text,
  description_en text,
  year text,
  tags text[],
  image_count integer default 1,
  display_order integer default 0
);

-- 2. Create Skills Table (If not exists)
CREATE TABLE IF NOT EXISTS public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  progress integer default 0,
  category text, -- 'mobile', 'backend', 'tools'
  icon_class text 
);

-- 3. Create General Info Table (Profile)
CREATE TABLE IF NOT EXISTS public.profile (
  id bigint generated by default as identity primary key,
  key text unique not null,
  value text,
  category text -- 'contact', 'hero', 'about'
);

-- MIGRATION: Add missing columns to existing projects table
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='projects' AND column_name='content_ar') THEN
        ALTER TABLE public.projects ADD COLUMN content_ar text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='projects' AND column_name='content_en') THEN
        ALTER TABLE public.projects ADD COLUMN content_en text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='projects' AND column_name='link') THEN
        ALTER TABLE public.projects ADD COLUMN link text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='projects' AND column_name='images') THEN
        ALTER TABLE public.projects ADD COLUMN images text[];
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='projects' AND column_name='display_order') THEN
        ALTER TABLE public.projects ADD COLUMN display_order integer DEFAULT 0;
    END IF;
END $$;

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies (wrapped in DO block to avoid 'already exists' error)
DO $$ 
BEGIN 
    -- Projects select
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable read access for all users' AND tablename = 'projects') THEN
        CREATE POLICY "Enable read access for all users" ON public.projects FOR SELECT USING (true);
    END IF;
    -- Projects all (authenticated)
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable all for authenticated' AND tablename = 'projects') THEN
        CREATE POLICY "Enable all for authenticated" ON public.projects FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;

    -- Skills select
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable read access for all users' AND tablename = 'skills') THEN
        CREATE POLICY "Enable read access for all users" ON public.skills FOR SELECT USING (true);
    END IF;
    -- Skills all (authenticated)
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable all for authenticated' AND tablename = 'skills') THEN
        CREATE POLICY "Enable all for authenticated" ON public.skills FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;

    -- Profile select
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable read access for all users' AND tablename = 'profile') THEN
        CREATE POLICY "Enable read access for all users" ON public.profile FOR SELECT USING (true);
    END IF;
    -- Profile all (authenticated)
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable all for authenticated' AND tablename = 'profile') THEN
        CREATE POLICY "Enable all for authenticated" ON public.profile FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
END $$;

-- 6. Insert Initial Data (Using UPSERT to avoid duplicate key errors)
INSERT INTO public.skills (name, progress, category, icon_class) 
VALUES 
('Flutter', 95, 'mobile', 'fab fa-flutter'),
('Dart', 90, 'mobile', 'fab fa-dart'),
('Node.js', 90, 'backend', 'fab fa-node-js')
ON CONFLICT DO NOTHING;

INSERT INTO public.profile (category, key, value) 
VALUES 
('contact', 'email', 'omer11.oo13@gmail.com'),
('contact', 'linkedin', 'https://www.linkedin.com/in/omer-al-dabbagh-5638a328b'),
('contact', 'github', 'https://github.com/omer2190')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
